import Navbar from '@/components/Navbar'
import Head from 'next/head'
import Hero from '@/components/Hero'
import About from '@/components/About'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'

import { motion } from 'framer-motion';


export default function Home() {
  return (
    <div id="home" className='bg-gradient-to-r from-black to-gray-900 h-screen'>
      <Head>
        <title>Senan Warnock</title>
        <meta name="Website for Senan Warnock" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Navbar />
      <Hero />
      <About />
      <Projects />
      <Contact />
      
    </div>
  )

}
